SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `budgetdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `budgetdb` ;

DROP TABLE IF EXISTS `budgetdb`.`budget`;
CREATE TABLE `budget` (
	`nid` INT NOT NULL AUTO_INCREMENT,
	`id_movie` INT NOT NULL,
	`budget_inicial` double,
	`budget_current` double,
	PRIMARY KEY (`nid`)
) ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




